"""adds users, dream_logs, tags table and dream_tags joint table

Revision ID: 60a634944bcf
Revises: fc314328253c
Create Date: 2023-10-10 09:43:45.999412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a634944bcf'
down_revision = 'fc314328253c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dream_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text_content', sa.String(length=500), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dream_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dream_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dream_log_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dream_log_id'], ['dream_logs.id'], name=op.f('fk_dream_tags_dream_log_id_dream_logs')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_dream_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dream_tags')
    op.drop_table('dream_logs')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
